language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls

script: nosetests --with-coverage --ignore-files=app.py --cover-package=amity

after_success: coveralls
